import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { assertPlatformAdmin, writeAudit, type PlatformAdmin } from "@/lib/platform-admin.server";
import type { Database } from "@/integrations/supabase/types";
import type { LifecycleStatus } from "@/lib/lifecycle";

type AccountStatus = Database["public"]["Enums"]["account_status"];

const LIFECYCLE_VALUES: LifecycleStatus[] = [
  "not_provisioned",
  "setup_payment_pending",
  "setup_paid",
  "provisioning",
  "ready",
  "active",
  "suspended",
  "cancelled",
  "archived",
];

/** Account status implied by a lifecycle move. Keeps the two models consistent. */
const ACCOUNT_FOR_LIFECYCLE: Partial<Record<LifecycleStatus, AccountStatus>> = {
  not_provisioned: "payment_required",
  setup_payment_pending: "payment_required",
  setup_paid: "setup_in_progress",
  provisioning: "setup_in_progress",
  ready: "setup_in_progress",
  active: "active",
  suspended: "suspended",
  cancelled: "cancelled",
  archived: "cancelled",
};

async function sha256(value: string) {
  const { createHash } = await import("node:crypto");
  return createHash("sha256").update(value).digest("hex");
}

async function randomToken(bytes = 32) {
  const { randomBytes } = await import("node:crypto");
  return randomBytes(bytes).toString("base64url");
}

async function randomPin() {
  const { randomInt } = await import("node:crypto");
  return String(randomInt(0, 1_000_000)).padStart(6, "0");
}

async function recordEvent(
  orgId: string,
  kind: string,
  title: string,
  detail?: string | null,
  actorEmail?: string | null,
) {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  await supabaseAdmin
    .from("customer_events")
    .insert({ organization_id: orgId, kind, title, detail: detail ?? null, actor_email: actorEmail ?? null });
}

export interface CreateClientInput {
  fullName: string;
  businessName: string;
  businessType?: string | undefined;
  email: string;
  phone?: string | undefined;
  country?: string | undefined;
  city?: string | undefined;
  address?: string | undefined;
  website?: string | undefined;
  gstNumber?: string | undefined;
  panNumber?: string | undefined;
  industry?: string | undefined;
  plan?: string | undefined;
  setupFee?: number | undefined; // paise
  monthlyFee?: number | undefined; // paise
  numberFee?: number | undefined; // paise
  walletOpeningBalance?: number | undefined; // paise
  notes?: string | undefined;
  internalNotes?: string | undefined;
}

/**
 * Creates a customer record from the admin control centre.
 *
 * The organization is created in `not_provisioned` so nothing unlocks until an
 * admin explicitly provisions it. `client_id` is generated by the database and
 * is immutable. No auth user is created here — the customer joins through a
 * hashed invitation.
 */
export const createClientAccount = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: CreateClientInput) => {
    if (!input?.businessName?.trim()) throw new Error("Business name is required");
    if (!input.email?.includes("@")) throw new Error("A valid email is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.write");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const email = data.email.trim().toLowerCase();

    const { data: clash } = await supabaseAdmin
      .from("organizations")
      .select("id, client_id, name")
      .ilike("contact_email", email)
      .maybeSingle();
    if (clash) throw new Error(`${clash.client_id} (${clash.name}) already uses that email`);

    const { data: org, error } = await supabaseAdmin
      .from("organizations")
      .insert({
        name: data.businessName.trim(),
        owner_id: admin.userId, // placeholder; transferred when the customer accepts the invitation
        created_by_admin: admin.userId,
        country: data.country ?? "IN",
        account_status: "payment_required",
        lifecycle_status: "not_provisioned",
        crm_stage: "lead",
        contact_name: data.fullName?.trim() || null,
        contact_email: email,
        contact_phone: data.phone?.trim() || null,
        city: data.city?.trim() || null,
        address: data.address?.trim() || null,
        website: data.website?.trim() || null,
        industry: data.industry?.trim() || null,
        business_type: data.businessType?.trim() || null,
        gst_number: data.gstNumber?.trim() || null,
        pan_number: data.panNumber?.trim() || null,
        internal_notes: data.internalNotes?.trim() || null,
      })
      .select("id, client_id, name")
      .single();
    if (error) throw error;

    await supabaseAdmin
      .from("subscriptions")
      .insert({ organization_id: org.id, plan: data.plan ?? "starter", status: "expired" });

    const overrides = [
      { key: "setup_fee", customer_amount: data.setupFee },
      { key: "monthly_plan", customer_amount: data.monthlyFee },
      { key: "phone_number", customer_amount: data.numberFee },
    ].filter((o) => typeof o.customer_amount === "number" && Number.isFinite(o.customer_amount));
    if (overrides.length) {
      await supabaseAdmin.from("organization_pricing_overrides").insert(
        overrides.map((o) => ({
          organization_id: org.id,
          key: o.key,
          customer_amount: Math.round(o.customer_amount as number),
          updated_by: admin.userId,
        })),
      );
    }

    if (data.walletOpeningBalance && data.walletOpeningBalance !== 0) {
      await supabaseAdmin.from("wallet_transactions").insert({
        organization_id: org.id,
        amount: Math.round(data.walletOpeningBalance),
        kind: "opening_balance",
        description: "Opening balance set at client creation",
        created_by: admin.userId,
      });
    }

    if (data.notes?.trim()) {
      await supabaseAdmin.from("crm_notes").insert({
        organization_id: org.id,
        admin_user_id: admin.userId,
        admin_email: admin.email,
        body: data.notes.trim(),
      });
    }

    await recordEvent(org.id, "lifecycle", "Client created", `Created by ${admin.email ?? "admin"}`, admin.email);
    await writeAudit(admin, {
      action: "CREATE_CLIENT",
      entityType: "organization",
      entityId: org.id,
      organizationId: org.id,
      newValue: { client_id: org.client_id, name: org.name, email },
      reason: "Client created from admin control centre",
    });

    return { id: org.id, clientId: org.client_id };
  });

/** Updates CRM / profile fields on a client. Client ID can never change. */
export const updateClientProfile = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string; patch: Record<string, string | null> }) => {
    if (!input?.orgId) throw new Error("orgId is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.write");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const allowed = [
      "name",
      "contact_name",
      "contact_email",
      "contact_phone",
      "city",
      "address",
      "website",
      "industry",
      "business_type",
      "gst_number",
      "pan_number",
      "internal_notes",
      "crm_stage",
      "follow_up_at",
      "last_contacted_at",
    ];
    const patch: Record<string, string | null> = {};
    for (const [k, v] of Object.entries(data.patch)) if (allowed.includes(k)) patch[k] = v === "" ? null : v;
    if (!Object.keys(patch).length) throw new Error("Nothing to update");

    const { data: before } = await supabaseAdmin.from("organizations").select("*").eq("id", data.orgId).maybeSingle();
    const { error } = await supabaseAdmin.from("organizations").update(patch as never).eq("id", data.orgId);
    if (error) throw error;

    await writeAudit(admin, {
      action: "UPDATE_CLIENT",
      entityType: "organization",
      entityId: data.orgId,
      organizationId: data.orgId,
      oldValue: before ? Object.fromEntries(Object.keys(patch).map((k) => [k, (before as never)[k]])) : null,
      newValue: patch,
      reason: "Client profile updated",
    });
    return { ok: true as const };
  });

/** Moves a client through the lifecycle and keeps account status in step. */
export const setClientLifecycle = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string; status: LifecycleStatus; reason: string }) => {
    if (!input?.orgId || !LIFECYCLE_VALUES.includes(input.status)) throw new Error("Invalid lifecycle status");
    if (!input.reason?.trim()) throw new Error("A reason is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.write");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const { data: before } = await supabaseAdmin
      .from("organizations")
      .select("lifecycle_status, account_status")
      .eq("id", data.orgId)
      .maybeSingle();

    const patch: Record<string, unknown> = {
      lifecycle_status: data.status,
      account_status: ACCOUNT_FOR_LIFECYCLE[data.status] ?? "payment_required",
    };
    if (data.status === "provisioning") patch["provisioned_at"] = new Date().toISOString();
    if (data.status === "active") {
      patch["activated_at"] = new Date().toISOString();
      patch["crm_stage"] = "customer";
    }
    if (data.status === "archived") patch["archived_at"] = new Date().toISOString();

    const { error } = await supabaseAdmin.from("organizations").update(patch as never).eq("id", data.orgId);
    if (error) throw error;

    await recordEvent(data.orgId, "lifecycle", `Lifecycle → ${data.status}`, data.reason, admin.email);
    await writeAudit(admin, {
      action: `LIFECYCLE_${data.status.toUpperCase()}`,
      entityType: "organization",
      entityId: data.orgId,
      organizationId: data.orgId,
      oldValue: before,
      newValue: patch,
      reason: data.reason,
    });
    return { ok: true as const };
  });

/**
 * Soft-deletes (archives) a client. Financial and operational history is never
 * removed: payments, wallet ledger, invoices, calls, usage and audit rows stay.
 */
export const archiveClient = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string; confirmation: string; reason: string }) => {
    if (!input?.orgId) throw new Error("orgId is required");
    if (!input.confirmation?.trim()) throw new Error("Type the Client ID to confirm");
    if (!input.reason?.trim()) throw new Error("A reason is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.write");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const { data: org } = await supabaseAdmin
      .from("organizations")
      .select("client_id, name, lifecycle_status")
      .eq("id", data.orgId)
      .maybeSingle();
    if (!org) throw new Error("Client not found");

    const typed = data.confirmation.trim().toLowerCase();
    if (typed !== org.client_id.toLowerCase() && typed !== org.name.toLowerCase()) {
      throw new Error("Confirmation does not match the Client ID or business name");
    }

    const { error } = await supabaseAdmin
      .from("organizations")
      .update({
        lifecycle_status: "archived",
        account_status: "cancelled",
        archived_at: new Date().toISOString(),
      })
      .eq("id", data.orgId);
    if (error) throw error;

    await supabaseAdmin
      .from("organization_invitations")
      .update({ revoked_at: new Date().toISOString() })
      .eq("organization_id", data.orgId)
      .is("accepted_at", null);

    await recordEvent(data.orgId, "lifecycle", "Client archived", data.reason, admin.email);
    await writeAudit(admin, {
      action: "ARCHIVE_CLIENT",
      entityType: "organization",
      entityId: data.orgId,
      organizationId: data.orgId,
      oldValue: org,
      newValue: { lifecycle_status: "archived" },
      reason: data.reason,
    });
    return { ok: true as const };
  });

/* ------------------------------------------------------------------ */
/* Invitations                                                         */
/* ------------------------------------------------------------------ */

export const listInvitations = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string }) => input)
  .handler(async ({ data, context }) => {
    await assertPlatformAdmin(context.supabase, context.userId, "customers.read");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: rows, error } = await supabaseAdmin
      .from("organization_invitations")
      .select("id, email, expires_at, accepted_at, revoked_at, failed_attempts, locked_until, last_sent_at, created_at")
      .eq("organization_id", data.orgId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return rows;
  });

/**
 * Issues an invitation. Only hashes are stored — the raw link and PIN are
 * returned exactly once to the admin and can never be read back.
 */
export const createInvitation = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string; email: string; expiresInHours?: number; withPin?: boolean }) => {
    if (!input?.orgId) throw new Error("orgId is required");
    if (!input.email?.includes("@")) throw new Error("A valid email is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.write");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const email = data.email.trim().toLowerCase();
    const token = await randomToken();
    const pin = data.withPin ? await randomPin() : null;
    const hours = Math.min(Math.max(data.expiresInHours ?? 72, 1), 720);

    // Supersede any outstanding invitation for this org.
    await supabaseAdmin
      .from("organization_invitations")
      .update({ revoked_at: new Date().toISOString() })
      .eq("organization_id", data.orgId)
      .is("accepted_at", null)
      .is("revoked_at", null);

    const { data: row, error } = await supabaseAdmin
      .from("organization_invitations")
      .insert({
        organization_id: data.orgId,
        email,
        token_hash: await sha256(token),
        pin_hash: pin ? await sha256(pin) : null,
        expires_at: new Date(Date.now() + hours * 3_600_000).toISOString(),
        created_by: admin.userId,
      })
      .select("id, expires_at")
      .single();
    if (error) throw error;

    await recordEvent(data.orgId, "access", "Invitation generated", `Sent to ${email}`, admin.email);
    await writeAudit(admin, {
      action: "CREATE_INVITATION",
      entityType: "invitation",
      entityId: row.id,
      organizationId: data.orgId,
      newValue: { email, expires_at: row.expires_at, pin: Boolean(pin) },
      reason: "Customer access invitation issued",
    });

    // Raw secrets are returned once, never persisted in readable form.
    return { id: row.id, token, pin, email, expiresAt: row.expires_at };
  });

export const revokeInvitation = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { invitationId: string; reason: string }) => {
    if (!input?.invitationId) throw new Error("invitationId is required");
    if (!input.reason?.trim()) throw new Error("A reason is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.write");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: row, error } = await supabaseAdmin
      .from("organization_invitations")
      .update({ revoked_at: new Date().toISOString() })
      .eq("id", data.invitationId)
      .select("organization_id, email")
      .single();
    if (error) throw error;

    await writeAudit(admin, {
      action: "REVOKE_INVITATION",
      entityType: "invitation",
      entityId: data.invitationId,
      organizationId: row.organization_id,
      newValue: { email: row.email, revoked: true },
      reason: data.reason,
    });
    return { ok: true as const };
  });

/**
 * Customer-side redemption. Requires a signed-in user whose email matches the
 * invitation. Attempts are counted and the invitation locks after 5 failures.
 */
export const acceptInvitation = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { token: string; pin?: string }) => {
    if (!input?.token) throw new Error("Invitation token is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const tokenHash = await sha256(data.token);

    const { data: invite } = await supabaseAdmin
      .from("organization_invitations")
      .select("*")
      .eq("token_hash", tokenHash)
      .maybeSingle();
    if (!invite) throw new Error("This invitation link is not valid");
    if (invite.revoked_at) throw new Error("This invitation has been revoked");
    if (invite.accepted_at) throw new Error("This invitation has already been used");
    if (new Date(invite.expires_at) < new Date()) throw new Error("This invitation has expired");
    if (invite.locked_until && new Date(invite.locked_until) > new Date()) {
      throw new Error("Too many failed attempts. Try again later or ask support to reset your access.");
    }

    const email = ((context.claims["email"] as string | undefined) ?? "").toLowerCase();
    const pinOk = !invite.pin_hash || (data.pin ? (await sha256(data.pin)) === invite.pin_hash : false);
    const emailOk = email && email === invite.email.toLowerCase();

    if (!pinOk || !emailOk) {
      const attempts = invite.failed_attempts + 1;
      await supabaseAdmin
        .from("organization_invitations")
        .update({
          failed_attempts: attempts,
          locked_until: attempts >= 5 ? new Date(Date.now() + 30 * 60_000).toISOString() : invite.locked_until,
        })
        .eq("id", invite.id);
      throw new Error(emailOk ? "Incorrect PIN" : "This invitation was issued to a different email address");
    }

    const { data: org } = await supabaseAdmin
      .from("organizations")
      .select("id, owner_id, created_by_admin, lifecycle_status")
      .eq("id", invite.organization_id)
      .maybeSingle();
    if (!org) throw new Error("This workspace no longer exists");

    // Hand ownership to the real customer if the record was admin-created.
    if (org.created_by_admin && org.owner_id === org.created_by_admin) {
      await supabaseAdmin.from("organizations").update({ owner_id: context.userId }).eq("id", org.id);
    }
    await supabaseAdmin
      .from("organization_members")
      .upsert(
        { organization_id: org.id, user_id: context.userId, role: "owner", invited_email: invite.email },
        { onConflict: "organization_id,user_id" },
      );

    await supabaseAdmin
      .from("organization_invitations")
      .update({ accepted_at: new Date().toISOString(), accepted_by: context.userId })
      .eq("id", invite.id);

    if (org.lifecycle_status === "ready") {
      await supabaseAdmin
        .from("organizations")
        .update({ lifecycle_status: "active", account_status: "active", activated_at: new Date().toISOString() })
        .eq("id", org.id);
    }

    await recordEvent(org.id, "access", "Invitation accepted", email, email);
    return { organizationId: org.id };
  });

/* ------------------------------------------------------------------ */
/* Admin support sessions (impersonation)                              */
/* ------------------------------------------------------------------ */

export const startSupportSession = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string; reason: string; minutes?: number }) => {
    if (!input?.orgId) throw new Error("orgId is required");
    if (!input.reason?.trim()) throw new Error("A reason is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.read");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { getRequestHeader } = await import("@tanstack/react-start/server");

    const token = await randomToken();
    const minutes = Math.min(Math.max(data.minutes ?? 30, 5), 120);
    const { data: row, error } = await supabaseAdmin
      .from("admin_support_sessions")
      .insert({
        admin_user_id: admin.userId,
        admin_email: admin.email,
        organization_id: data.orgId,
        token_hash: await sha256(token),
        reason: data.reason,
        ip_address: getRequestHeader("x-forwarded-for") ?? null,
        user_agent: getRequestHeader("user-agent") ?? null,
        expires_at: new Date(Date.now() + minutes * 60_000).toISOString(),
      })
      .select("id, expires_at")
      .single();
    if (error) throw error;

    await recordEvent(data.orgId, "support", "Admin support session started", data.reason, admin.email);
    await writeAudit(admin, {
      action: "IMPERSONATE_CLIENT",
      entityType: "support_session",
      entityId: row.id,
      organizationId: data.orgId,
      newValue: { expires_at: row.expires_at },
      reason: data.reason,
    });
    return { sessionId: row.id, token, expiresAt: row.expires_at };
  });

export const endSupportSession = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { sessionId: string }) => {
    if (!input?.sessionId) throw new Error("sessionId is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.read");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: row, error } = await supabaseAdmin
      .from("admin_support_sessions")
      .update({ ended_at: new Date().toISOString() })
      .eq("id", data.sessionId)
      .eq("admin_user_id", admin.userId)
      .select("organization_id")
      .single();
    if (error) throw error;

    await writeAudit(admin, {
      action: "END_IMPERSONATION",
      entityType: "support_session",
      entityId: data.sessionId,
      organizationId: row.organization_id,
      reason: "Support session ended",
    });
    return { ok: true as const };
  });

/**
 * Read-only customer workspace snapshot for an active support session. The
 * admin never gains the customer's credentials and cannot write through this
 * path — every field is fetched server-side after re-verifying the session.
 */
export const getSupportSessionView = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { sessionId: string; token: string }) => {
    if (!input?.sessionId || !input.token) throw new Error("A valid support session is required");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin = await assertPlatformAdmin(context.supabase, context.userId, "customers.read");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const { data: sess } = await supabaseAdmin
      .from("admin_support_sessions")
      .select("*")
      .eq("id", data.sessionId)
      .maybeSingle();
    if (!sess || sess.admin_user_id !== admin.userId) throw new Error("Support session not found");
    if (sess.ended_at) throw new Error("This support session has ended");
    if (new Date(sess.expires_at) < new Date()) throw new Error("This support session has expired");
    if ((await sha256(data.token)) !== sess.token_hash) throw new Error("Invalid support session token");

    const orgId = sess.organization_id;
    const [org, business, numbers, calls, leads, wallet, agent] = await Promise.all([
      supabaseAdmin.from("organizations").select("*").eq("id", orgId).maybeSingle(),
      supabaseAdmin.from("businesses").select("*").eq("organization_id", orgId).maybeSingle(),
      supabaseAdmin.from("phone_numbers").select("*").eq("organization_id", orgId),
      supabaseAdmin
        .from("call_logs")
        .select("id, direction, status, duration_seconds, started_at, summary")
        .eq("organization_id", orgId)
        .order("started_at", { ascending: false })
        .limit(20),
      supabaseAdmin
        .from("leads")
        .select("id, name, phone, status, score, created_at")
        .eq("organization_id", orgId)
        .order("created_at", { ascending: false })
        .limit(20),
      supabaseAdmin.from("wallet_transactions").select("amount").eq("organization_id", orgId),
      supabaseAdmin.from("agent_configs").select("*").eq("organization_id", orgId).maybeSingle(),
    ]);

    return {
      session: { id: sess.id, expiresAt: sess.expires_at, adminEmail: sess.admin_email },
      organization: org.data,
      business: business.data,
      numbers: numbers.data ?? [],
      calls: calls.data ?? [],
      leads: leads.data ?? [],
      walletBalance: (wallet.data ?? []).reduce((s, t) => s + t.amount, 0),
      agent: agent.data,
    };
  });

/* ------------------------------------------------------------------ */
/* CRM                                                                  */
/* ------------------------------------------------------------------ */

export const listCrm = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string }) => input)
  .handler(async ({ data, context }) => {
    await assertPlatformAdmin(context.supabase, context.userId, "customers.read");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const [notes, events] = await Promise.all([
      supabaseAdmin
        .from("crm_notes")
        .select("*")
        .eq("organization_id", data.orgId)
        .order("created_at", { ascending: false }),
      supabaseAdmin
        .from("customer_events")
        .select("*")
        .eq("organization_id", data.orgId)
        .order("created_at", { ascending: false })
        .limit(100),
    ]);
    return { notes: notes.data ?? [], events: events.data ?? [] };
  });

export const addCrmNote = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { orgId: string; body: string; followUpAt?: string | null }) => {
    if (!input?.orgId) throw new Error("orgId is required");
    if (!input.body?.trim()) throw new Error("Note cannot be empty");
    return input;
  })
  .handler(async ({ data, context }) => {
    const admin: PlatformAdmin = await assertPlatformAdmin(context.supabase, context.userId, "customers.write");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { error } = await supabaseAdmin.from("crm_notes").insert({
      organization_id: data.orgId,
      admin_user_id: admin.userId,
      admin_email: admin.email,
      body: data.body.trim(),
      follow_up_at: data.followUpAt ?? null,
    });
    if (error) throw error;
    if (data.followUpAt) {
      await supabaseAdmin.from("organizations").update({ follow_up_at: data.followUpAt }).eq("id", data.orgId);
    }
    await supabaseAdmin
      .from("organizations")
      .update({ last_contacted_at: new Date().toISOString() })
      .eq("id", data.orgId);
    return { ok: true as const };
  });
