import { useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Plus } from "lucide-react";
import { createClientAccount } from "@/lib/admin-clients.functions";
import { BUSINESS_TYPES } from "@/lib/business-types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

const empty = {
  fullName: "",
  businessName: "",
  businessType: "",
  email: "",
  phone: "",
  country: "IN",
  city: "",
  address: "",
  website: "",
  gstNumber: "",
  panNumber: "",
  industry: "",
  plan: "starter",
  setupFee: "",
  monthlyFee: "",
  numberFee: "",
  walletOpeningBalance: "",
  notes: "",
  internalNotes: "",
};

const rupeesToPaise = (value: string) => {
  if (!value.trim()) return undefined;
  const n = Number(value);
  if (!Number.isFinite(n) || n < 0) throw new Error("Amounts must be positive numbers");
  return Math.round(n * 100);
};

/** Admin-side client creation. Client ID is generated by the database. */
export function CreateClientDialog() {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState(empty);
  const [busy, setBusy] = useState(false);
  const create = useServerFn(createClientAccount);
  const queryClient = useQueryClient();
  const navigate = useNavigate();

  const set = (key: keyof typeof empty) => (e: { target: { value: string } }) =>
    setForm((f) => ({ ...f, [key]: e.target.value }));

  const submit = async () => {
    setBusy(true);
    try {
      const result = await create({
        data: {
          fullName: form.fullName,
          businessName: form.businessName,
          businessType: form.businessType,
          email: form.email,
          phone: form.phone,
          country: form.country,
          city: form.city,
          address: form.address,
          website: form.website,
          gstNumber: form.gstNumber,
          panNumber: form.panNumber,
          industry: form.industry,
          plan: form.plan,
          setupFee: rupeesToPaise(form.setupFee),
          monthlyFee: rupeesToPaise(form.monthlyFee),
          numberFee: rupeesToPaise(form.numberFee),
          walletOpeningBalance: rupeesToPaise(form.walletOpeningBalance),
          notes: form.notes,
          internalNotes: form.internalNotes,
        },
      });
      toast.success(`Client ${result.clientId} created`);
      setForm(empty);
      setOpen(false);
      await queryClient.invalidateQueries({ queryKey: ["admin-customers"] });
      navigate({ to: "/admin/customers/$orgId", params: { orgId: result.id } });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Could not create client");
    } finally {
      setBusy(false);
    }
  };

  const field = (key: keyof typeof empty, label: string, props: Record<string, unknown> = {}) => (
    <div className="space-y-1.5">
      <Label className="text-xs text-muted-foreground">{label}</Label>
      <Input value={form[key]} onChange={set(key)} {...props} />
    </div>
  );

  return (
    <Dialog open={open} onOpenChange={(v) => !busy && setOpen(v)}>
      <DialogTrigger asChild>
        <Button size="sm">
          <Plus className="mr-1.5 size-3.5" /> Create client
        </Button>
      </DialogTrigger>
      <DialogContent className="max-h-[88vh] max-w-3xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create client</DialogTitle>
          <DialogDescription>
            A permanent Client ID (VAA-000000) is generated automatically. The workspace stays unprovisioned until you
            explicitly move it through the lifecycle.
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-4 sm:grid-cols-2">
          {field("businessName", "Business name *", { placeholder: "Smile Dental" })}
          {field("fullName", "Contact person")}
          {field("email", "Email *", { type: "email", placeholder: "owner@business.in" })}
          {field("phone", "Phone")}
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">Business type</Label>
            <select
              value={form.businessType}
              onChange={set("businessType")}
              className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"
            >
              <option value="">Not set</option>
              {BUSINESS_TYPES.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.label}
                </option>
              ))}
            </select>
          </div>
          {field("industry", "Industry")}
          {field("city", "City")}
          {field("country", "Country")}
          <div className="sm:col-span-2">{field("address", "Address")}</div>
          {field("website", "Website")}
          {field("plan", "Plan")}
          {field("gstNumber", "GSTIN")}
          {field("panNumber", "PAN")}
          {field("setupFee", "Setup fee (₹)", { inputMode: "decimal", placeholder: "leave blank for platform default" })}
          {field("monthlyFee", "Monthly fee (₹)", { inputMode: "decimal" })}
          {field("numberFee", "Number fee (₹/month)", { inputMode: "decimal" })}
          {field("walletOpeningBalance", "Wallet opening balance (₹)", { inputMode: "decimal" })}
          <div className="space-y-1.5 sm:col-span-2">
            <Label className="text-xs text-muted-foreground">Notes (CRM)</Label>
            <Textarea rows={2} value={form.notes} onChange={set("notes")} />
          </div>
          <div className="space-y-1.5 sm:col-span-2">
            <Label className="text-xs text-muted-foreground">Internal admin notes (never shown to the customer)</Label>
            <Textarea rows={2} value={form.internalNotes} onChange={set("internalNotes")} />
          </div>
        </div>

        <DialogFooter>
          <Button variant="ghost" disabled={busy} onClick={() => setOpen(false)}>
            Cancel
          </Button>
          <Button disabled={busy} onClick={submit}>
            {busy ? "Creating…" : "Create client"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
