/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminCallsRouteImport } from './routes/admin.calls'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDemoRequestsRouteImport } from './routes/admin.demo-requests'
import { Route as AdminMarginsRouteImport } from './routes/admin.margins'
import { Route as AdminNumbersRouteImport } from './routes/admin.numbers'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminWebsiteAiRouteImport } from './routes/admin.website-ai'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppBusinessRouteImport } from './routes/app.business'
import { Route as AppCallsRouteImport } from './routes/app.calls'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppNumbersRouteImport } from './routes/app.numbers'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersOrgIdRouteImport } from './routes/admin.customers.$orgId'
import { Route as AppCampaignsCampaignIdRouteImport } from './routes/app.campaigns.$campaignId'
import { Route as AppCampaignsNewRouteImport } from './routes/app.campaigns.new'
import { Route as ApiPublicCronDispatchCampaignsRouteImport } from './routes/api/public/cron/dispatch-campaigns'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as ApiPublicWebhooksTelephonyRouteImport } from './routes/api/public/webhooks/telephony'
import { Route as ApiPublicWebhooksExotelMediaTokenRouteImport } from './routes/api/public/webhooks/exotel.media-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallsRoute = AdminCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRequestsRoute = AdminDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarginsRoute = AdminMarginsRouteImport.update({
  id: '/margins',
  path: '/margins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNumbersRoute = AdminNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteAiRoute = AdminWebsiteAiRouteImport.update({
  id: '/website-ai',
  path: '/website-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppNumbersRoute = AppNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersOrgIdRoute = AdminCustomersOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AppCampaignsCampaignIdRoute = AppCampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const ApiPublicCronDispatchCampaignsRoute =
  ApiPublicCronDispatchCampaignsRouteImport.update({
    id: '/api/public/cron/dispatch-campaigns',
    path: '/api/public/cron/dispatch-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTelephonyRoute =
  ApiPublicWebhooksTelephonyRouteImport.update({
    id: '/api/public/webhooks/telephony',
    path: '/api/public/webhooks/telephony',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksExotelMediaTokenRoute =
  ApiPublicWebhooksExotelMediaTokenRouteImport.update({
    id: '/api/public/webhooks/exotel/media-token',
    path: '/api/public/webhooks/exotel/media-token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/numbers': typeof AdminNumbersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/website-ai': typeof AdminWebsiteAiRoute
  '/app/agent': typeof AppAgentRoute
  '/app/billing': typeof AppBillingRoute
  '/app/business': typeof AppBusinessRoute
  '/app/calls': typeof AppCallsRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/contacts': typeof AppContactsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/numbers': typeof AppNumbersRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/customers/$orgId': typeof AdminCustomersOrgIdRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/api/public/cron/dispatch-campaigns': typeof ApiPublicCronDispatchCampaignsRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/api/public/webhooks/telephony': typeof ApiPublicWebhooksTelephonyRoute
  '/api/public/webhooks/exotel/media-token': typeof ApiPublicWebhooksExotelMediaTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/numbers': typeof AdminNumbersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/website-ai': typeof AdminWebsiteAiRoute
  '/app/agent': typeof AppAgentRoute
  '/app/billing': typeof AppBillingRoute
  '/app/business': typeof AppBusinessRoute
  '/app/calls': typeof AppCallsRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/contacts': typeof AppContactsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/numbers': typeof AppNumbersRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/customers/$orgId': typeof AdminCustomersOrgIdRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/api/public/cron/dispatch-campaigns': typeof ApiPublicCronDispatchCampaignsRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/api/public/webhooks/telephony': typeof ApiPublicWebhooksTelephonyRoute
  '/api/public/webhooks/exotel/media-token': typeof ApiPublicWebhooksExotelMediaTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/numbers': typeof AdminNumbersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/website-ai': typeof AdminWebsiteAiRoute
  '/app/agent': typeof AppAgentRoute
  '/app/billing': typeof AppBillingRoute
  '/app/business': typeof AppBusinessRoute
  '/app/calls': typeof AppCallsRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/contacts': typeof AppContactsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/numbers': typeof AppNumbersRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/customers/$orgId': typeof AdminCustomersOrgIdRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/api/public/cron/dispatch-campaigns': typeof ApiPublicCronDispatchCampaignsRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/api/public/webhooks/telephony': typeof ApiPublicWebhooksTelephonyRoute
  '/api/public/webhooks/exotel/media-token': typeof ApiPublicWebhooksExotelMediaTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/reset-password'
    | '/account/settings'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/calls'
    | '/admin/customers'
    | '/admin/demo-requests'
    | '/admin/margins'
    | '/admin/numbers'
    | '/admin/pricing'
    | '/admin/refunds'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/admin/wallets'
    | '/admin/website-ai'
    | '/app/agent'
    | '/app/billing'
    | '/app/business'
    | '/app/calls'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/knowledge'
    | '/app/leads'
    | '/app/numbers'
    | '/app/onboarding'
    | '/app/settings'
    | '/auth/callback'
    | '/account/'
    | '/admin/'
    | '/app/'
    | '/admin/customers/$orgId'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/admin/customers/'
    | '/api/public/cron/dispatch-campaigns'
    | '/api/public/webhooks/razorpay'
    | '/api/public/webhooks/telephony'
    | '/api/public/webhooks/exotel/media-token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/reset-password'
    | '/account/settings'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/calls'
    | '/admin/demo-requests'
    | '/admin/margins'
    | '/admin/numbers'
    | '/admin/pricing'
    | '/admin/refunds'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/admin/wallets'
    | '/admin/website-ai'
    | '/app/agent'
    | '/app/billing'
    | '/app/business'
    | '/app/calls'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/knowledge'
    | '/app/leads'
    | '/app/numbers'
    | '/app/onboarding'
    | '/app/settings'
    | '/auth/callback'
    | '/account'
    | '/admin'
    | '/app'
    | '/admin/customers/$orgId'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/admin/customers'
    | '/api/public/cron/dispatch-campaigns'
    | '/api/public/webhooks/razorpay'
    | '/api/public/webhooks/telephony'
    | '/api/public/webhooks/exotel/media-token'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/reset-password'
    | '/account/settings'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/calls'
    | '/admin/customers'
    | '/admin/demo-requests'
    | '/admin/margins'
    | '/admin/numbers'
    | '/admin/pricing'
    | '/admin/refunds'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/admin/wallets'
    | '/admin/website-ai'
    | '/app/agent'
    | '/app/billing'
    | '/app/business'
    | '/app/calls'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/knowledge'
    | '/app/leads'
    | '/app/numbers'
    | '/app/onboarding'
    | '/app/settings'
    | '/auth/callback'
    | '/account/'
    | '/admin/'
    | '/app/'
    | '/admin/customers/$orgId'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/admin/customers/'
    | '/api/public/cron/dispatch-campaigns'
    | '/api/public/webhooks/razorpay'
    | '/api/public/webhooks/telephony'
    | '/api/public/webhooks/exotel/media-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCronDispatchCampaignsRoute: typeof ApiPublicCronDispatchCampaignsRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
  ApiPublicWebhooksTelephonyRoute: typeof ApiPublicWebhooksTelephonyRoute
  ApiPublicWebhooksExotelMediaTokenRoute: typeof ApiPublicWebhooksExotelMediaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calls': {
      id: '/admin/calls'
      path: '/calls'
      fullPath: '/admin/calls'
      preLoaderRoute: typeof AdminCallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo-requests': {
      id: '/admin/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminDemoRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/margins': {
      id: '/admin/margins'
      path: '/margins'
      fullPath: '/admin/margins'
      preLoaderRoute: typeof AdminMarginsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/numbers': {
      id: '/admin/numbers'
      path: '/numbers'
      fullPath: '/admin/numbers'
      preLoaderRoute: typeof AdminNumbersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website-ai': {
      id: '/admin/website-ai'
      path: '/website-ai'
      fullPath: '/admin/website-ai'
      preLoaderRoute: typeof AdminWebsiteAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/business': {
      id: '/app/business'
      path: '/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls': {
      id: '/app/calls'
      path: '/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/numbers': {
      id: '/app/numbers'
      path: '/numbers'
      fullPath: '/app/numbers'
      preLoaderRoute: typeof AppNumbersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/$orgId': {
      id: '/admin/customers/$orgId'
      path: '/$orgId'
      fullPath: '/admin/customers/$orgId'
      preLoaderRoute: typeof AdminCustomersOrgIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/app/campaigns/$campaignId': {
      id: '/app/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/app/campaigns/$campaignId'
      preLoaderRoute: typeof AppCampaignsCampaignIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/app/campaigns/new': {
      id: '/app/campaigns/new'
      path: '/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/api/public/cron/dispatch-campaigns': {
      id: '/api/public/cron/dispatch-campaigns'
      path: '/api/public/cron/dispatch-campaigns'
      fullPath: '/api/public/cron/dispatch-campaigns'
      preLoaderRoute: typeof ApiPublicCronDispatchCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/telephony': {
      id: '/api/public/webhooks/telephony'
      path: '/api/public/webhooks/telephony'
      fullPath: '/api/public/webhooks/telephony'
      preLoaderRoute: typeof ApiPublicWebhooksTelephonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/exotel/media-token': {
      id: '/api/public/webhooks/exotel/media-token'
      path: '/api/public/webhooks/exotel/media-token'
      fullPath: '/api/public/webhooks/exotel/media-token'
      preLoaderRoute: typeof ApiPublicWebhooksExotelMediaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminCustomersRouteChildren {
  AdminCustomersOrgIdRoute: typeof AdminCustomersOrgIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersOrgIdRoute: AdminCustomersOrgIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCallsRoute: typeof AdminCallsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDemoRequestsRoute: typeof AdminDemoRequestsRoute
  AdminMarginsRoute: typeof AdminMarginsRoute
  AdminNumbersRoute: typeof AdminNumbersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWebsiteAiRoute: typeof AdminWebsiteAiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCallsRoute: AdminCallsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDemoRequestsRoute: AdminDemoRequestsRoute,
  AdminMarginsRoute: AdminMarginsRoute,
  AdminNumbersRoute: AdminNumbersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWebsiteAiRoute: AdminWebsiteAiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCampaignsRouteChildren {
  AppCampaignsCampaignIdRoute: typeof AppCampaignsCampaignIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsCampaignIdRoute: AppCampaignsCampaignIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppCallsRoute: typeof AppCallsRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppContactsRoute: typeof AppContactsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppNumbersRoute: typeof AppNumbersRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppBillingRoute: AppBillingRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppCallsRoute: AppCallsRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppContactsRoute: AppContactsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppNumbersRoute: AppNumbersRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCronDispatchCampaignsRoute: ApiPublicCronDispatchCampaignsRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
  ApiPublicWebhooksTelephonyRoute: ApiPublicWebhooksTelephonyRoute,
  ApiPublicWebhooksExotelMediaTokenRoute:
    ApiPublicWebhooksExotelMediaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
