-- Instagram integration (Phase 5) — schema only.
--
-- Additive only. Does NOT alter whatsapp_connections / whatsapp_conversations
-- / whatsapp_messages / agent_configs / contacts / payment_requests in any
-- way (per the approved Phase 5 architecture: no destructive migration, no
-- table unification with WhatsApp in v1, no Instagram-specific payment
-- tables). New tables mirror the WhatsApp shape where the concept is
-- genuinely shared (organization_id, contact_id, status, direction,
-- content, metadata, occurred_at) and diverge only where Instagram's own
-- identifiers/vocabulary require it:
--   - bot assignment: agent_configs (same existing 1-bot-per-business model
--     instagram_connections.agent_config_id points at, exactly like
--     whatsapp_connections.agent_config_id — no second "bot" concept)
--   - webhook idempotency (whole-payload level): the existing generic
--     webhook_events table, provider='instagram' — no collision with the
--     already-used 'sarvam' / 'exotel' / 'razorpay' / 'whatsapp' values
--   - contacts: linkage is deferred exactly as it already is for WhatsApp
--     (instagram_conversations.contact_id/instagram_messages.contact_id are
--     nullable FKs to the existing contacts table; no code path populates
--     them in v1 — contacts.phone is NOT NULL + E.164-checked, and an
--     Instagram-only customer has no phone number, so forcing a contacts
--     row here would mean inventing a placeholder phone and polluting the
--     existing phone-based dedup. Deferred to a future phase's generic
--     channel-identity design, matching the current, actual WhatsApp
--     behavior rather than its aspirational schema comment.)
--   - feature gating: the existing feature_locked() machinery, via the new
--     "instagram" key added to src/lib/features.ts PLATFORM_FEATURES
--
-- No plaintext secret ever lands in a customer-readable column.
-- instagram_connections.access_token_ciphertext holds AES-256-GCM
-- ciphertext produced by application code (instagram-token-crypto.
-- server.ts) using a dedicated server-only encryption key
-- (INSTAGRAM_CREDENTIAL_ENCRYPTION_KEY) — deliberately a separate key from
-- WHATSAPP_CREDENTIAL_ENCRYPTION_KEY/GOOGLE_CALENDAR_CREDENTIAL_ENCRYPTION_KEY/
-- RAZORPAY_CREDENTIAL_ENCRYPTION_KEY, same "rotating one provider's key
-- never touches another's already-stored ciphertext" convention already
-- established for every other credential store in this codebase.

-- ============================================================
-- 1. instagram_connections — one row per connected Instagram professional
--    (Business/Creator) account, linked via its Facebook Page (Meta's own
--    requirement for Tech-Provider-managed Instagram messaging: an IG
--    professional account must be linked to a Facebook Page for the
--    Graph API to manage it on a tenant's behalf).
-- ============================================================
CREATE TABLE public.instagram_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  business_id UUID REFERENCES public.businesses(id) ON DELETE SET NULL,
  -- The bot handling this connection. Direct FK to agent_configs, not a
  -- derived join through business_id — same convention as
  -- whatsapp_connections.agent_config_id: a connection can exist before a
  -- bot is chosen, and reassigning the bot must not require moving the
  -- connection to a different business.
  agent_config_id UUID REFERENCES public.agent_configs(id) ON DELETE SET NULL,

  -- Meta-side identifiers. Both are Meta's own opaque numeric-string IDs,
  -- never generated by ClickAI. Kept as text, matching whatsapp_connections'
  -- waba_id/phone_number_id convention.
  instagram_business_account_id TEXT NOT NULL,
  facebook_page_id TEXT NOT NULL,
  username TEXT,
  display_name TEXT,
  profile_picture_url TEXT,

  status TEXT NOT NULL DEFAULT 'not_connected',

  -- AES-256-GCM ciphertext (see instagram-token-crypto.server.ts),
  -- produced and consumed only by server-side code holding
  -- INSTAGRAM_CREDENTIAL_ENCRYPTION_KEY. NULL until onboarding completes.
  access_token_ciphertext TEXT,

  webhook_subscribed BOOLEAN NOT NULL DEFAULT false,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_error TEXT,
  last_connected_at TIMESTAMPTZ,
  disconnected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$ BEGIN
  ALTER TABLE public.instagram_connections ADD CONSTRAINT instagram_connections_status_check
    CHECK (status IN ('not_connected', 'connecting', 'connected', 'error', 'disconnected', 'needs_attention'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- A given Meta IG business account id must never be live for more than one
-- ClickAI tenant at once — same cross-organization uniqueness rule
-- whatsapp_connections already applies to phone_number_id. Disconnected
-- rows are excluded so a reconnect (same or different tenant) never blocks
-- forever on a stale row.
CREATE UNIQUE INDEX idx_instagram_connections_ig_account_live
  ON public.instagram_connections (instagram_business_account_id) WHERE status <> 'disconnected';

CREATE INDEX idx_instagram_connections_org ON public.instagram_connections (organization_id);
CREATE INDEX idx_instagram_connections_page ON public.instagram_connections (facebook_page_id);

GRANT SELECT, UPDATE (agent_config_id) ON public.instagram_connections TO authenticated;
GRANT ALL ON public.instagram_connections TO service_role;
ALTER TABLE public.instagram_connections ENABLE ROW LEVEL SECURITY;

-- Customers may read their own connections and change which bot handles
-- one — the same one self-service mutation whatsapp_connections allows.
-- Every other field (status, tokens, Meta identifiers) is written
-- exclusively by server-side code (onboarding handler, webhook, dashboard
-- server functions), all via supabaseAdmin, which bypasses RLS entirely.
CREATE POLICY "tenant instagram connections read" ON public.instagram_connections
  FOR SELECT TO authenticated USING (public.is_org_member(organization_id));
CREATE POLICY "tenant instagram connections assign bot" ON public.instagram_connections
  FOR UPDATE TO authenticated
  USING (public.is_org_member(organization_id))
  WITH CHECK (public.is_org_member(organization_id));

-- Column-level protection: explicit SELECT column list excluding
-- access_token_ciphertext, same belt-and-suspenders pattern
-- whatsapp_connections/razorpay_connections already use — a future
-- `select("*")` on this table from customer-facing code cannot leak the
-- ciphertext column.
REVOKE SELECT ON public.instagram_connections FROM authenticated;
GRANT SELECT (
  id, organization_id, business_id, agent_config_id, instagram_business_account_id,
  facebook_page_id, username, display_name, profile_picture_url, status,
  webhook_subscribed, metadata, last_error, last_connected_at, disconnected_at,
  created_at, updated_at
) ON public.instagram_connections TO authenticated;

CREATE TRIGGER trg_instagram_connections_updated BEFORE UPDATE ON public.instagram_connections
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- 2. instagram_conversations — one per (connection, customer IG-scoped id)
-- ============================================================
CREATE TABLE public.instagram_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  instagram_connection_id UUID NOT NULL REFERENCES public.instagram_connections(id) ON DELETE CASCADE,
  -- Deferred, exactly as whatsapp_conversations.contact_id already is in
  -- practice (see this migration's header comment) — no code path
  -- populates this in v1.
  contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
  -- The customer's Instagram-Scoped ID (IGSID) — Meta's own opaque,
  -- per-app identifier for the person messaging this account. Analogous to
  -- whatsapp_conversations.wa_id, but never a phone number or public
  -- username (Meta does not expose either through the messaging API).
  ig_scoped_id TEXT NOT NULL,
  customer_username TEXT,
  customer_display_name TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  unread_count INTEGER NOT NULL DEFAULT 0,
  last_message_at TIMESTAMPTZ,
  last_message_preview TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- One conversation per customer per connected account. Tenant isolation
  -- falls out naturally: instagram_connection_id already belongs to
  -- exactly one organization.
  UNIQUE (instagram_connection_id, ig_scoped_id)
);

DO $$ BEGIN
  ALTER TABLE public.instagram_conversations ADD CONSTRAINT instagram_conversations_status_check
    CHECK (status IN ('open', 'closed'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX idx_instagram_conversations_org ON public.instagram_conversations (organization_id, last_message_at DESC);
CREATE INDEX idx_instagram_conversations_connection ON public.instagram_conversations (instagram_connection_id);
CREATE INDEX idx_instagram_conversations_contact ON public.instagram_conversations (contact_id);

GRANT SELECT ON public.instagram_conversations TO authenticated;
GRANT ALL ON public.instagram_conversations TO service_role;
ALTER TABLE public.instagram_conversations ENABLE ROW LEVEL SECURITY;
-- Read-only for customers — every write happens server-side (webhook
-- handler, outbound-send service), matching whatsapp_conversations.
CREATE POLICY "tenant instagram conversations read" ON public.instagram_conversations
  FOR SELECT TO authenticated USING (public.is_org_member(organization_id));

CREATE TRIGGER trg_instagram_conversations_updated BEFORE UPDATE ON public.instagram_conversations
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- 3. instagram_messages
-- ============================================================
CREATE TABLE public.instagram_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  instagram_connection_id UUID NOT NULL REFERENCES public.instagram_connections(id) ON DELETE CASCADE,
  conversation_id UUID NOT NULL REFERENCES public.instagram_conversations(id) ON DELETE CASCADE,
  contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
  -- Meta's own message id. NULL only for a rare synthetic system row, so
  -- the uniqueness index below is a partial index, matching
  -- whatsapp_messages' wa_message_id convention.
  ig_message_id TEXT,
  direction TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'text',
  content TEXT,
  status TEXT NOT NULL DEFAULT 'received',
  error_message TEXT,
  -- Bot-loop protection (spec: "never process ClickAI's own outbound
  -- message as a new customer message"). Set true only when the inbound
  -- webhook payload itself carries Meta's `is_echo` flag (best-effort — not
  -- independently confirmed live in this session, see
  -- instagram-inbound.server.ts's module doc). The PRIMARY, always-reliable
  -- guard is independent of this flag: instagram-inbound.server.ts compares
  -- the webhook event's sender id against this connection's own
  -- instagram_business_account_id and never persists or reacts to a
  -- message/comment authored by the connected account itself.
  is_echo BOOLEAN NOT NULL DEFAULT false,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$ BEGIN
  ALTER TABLE public.instagram_messages ADD CONSTRAINT instagram_messages_direction_check
    CHECK (direction IN ('inbound', 'outbound'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  -- Instagram's own message vocabulary — deliberately NOT copied
  -- byte-for-byte from whatsapp_messages_type_check: no 'template' or
  -- 'interactive' (WhatsApp-only concepts), no 'document' (Instagram
  -- messaging does not support arbitrary document attachments); adds
  -- 'story_mention'/'story_reply'/'share', which are genuinely
  -- Instagram-specific message shapes. Only what this phase's inbound
  -- handler can actually parse or is required to record — widen in a
  -- later migration if outbound media send is built.
  ALTER TABLE public.instagram_messages ADD CONSTRAINT instagram_messages_type_check
    CHECK (message_type IN ('text', 'image', 'video', 'audio', 'share', 'story_mention', 'story_reply', 'unsupported'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.instagram_messages ADD CONSTRAINT instagram_messages_status_check
    CHECK (status IN ('received', 'queued', 'sent', 'delivered', 'read', 'failed'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Idempotency for the webhook path, defense-in-depth alongside the outer
-- webhook_events(provider, event_id) dedupe — same belt-and-suspenders
-- reasoning as whatsapp_messages' idx_whatsapp_messages_connection_wamid.
CREATE UNIQUE INDEX idx_instagram_messages_connection_igmid
  ON public.instagram_messages (instagram_connection_id, ig_message_id) WHERE ig_message_id IS NOT NULL;

CREATE INDEX idx_instagram_messages_conversation ON public.instagram_messages (conversation_id, occurred_at DESC);
CREATE INDEX idx_instagram_messages_org ON public.instagram_messages (organization_id);

GRANT SELECT ON public.instagram_messages TO authenticated;
GRANT ALL ON public.instagram_messages TO service_role;
ALTER TABLE public.instagram_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant instagram messages read" ON public.instagram_messages
  FOR SELECT TO authenticated USING (public.is_org_member(organization_id));

-- ============================================================
-- 4. instagram_automation_rules — minimal v1 comment->DM automation
--    (spec explicitly: "do not build a visual workflow builder, arbitrary
--    rule DSL, or complex automation graph" — one flat table, no rule
--    engine). Customer-configurable directly from the dashboard, same as
--    agent_configs/businesses (pattern A: FOR ALL, is_org_member).
-- ============================================================
CREATE TABLE public.instagram_automation_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  business_id UUID REFERENCES public.businesses(id) ON DELETE SET NULL,
  instagram_connection_id UUID NOT NULL REFERENCES public.instagram_connections(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Untitled rule',
  -- 'comment_keyword': trigger_config.keywords (text[]) must appear in the
  --   comment; 'comment_any': every comment on this connection matches.
  -- Either may additionally scope to one post via trigger_config.postId.
  trigger_type TEXT NOT NULL,
  trigger_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- 'public_reply': action_config.replyText, posted as a public comment
  --   reply. 'private_dm': action_config.dmText, sent as a fixed DM.
  --   'ai_dm': no fixed text — routes to the shared AI agent core exactly
  --   like a normal inbound DM (see instagram-automation.server.ts).
  action_type TEXT NOT NULL,
  action_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$ BEGIN
  ALTER TABLE public.instagram_automation_rules ADD CONSTRAINT instagram_automation_rules_trigger_type_check
    CHECK (trigger_type IN ('comment_keyword', 'comment_any'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.instagram_automation_rules ADD CONSTRAINT instagram_automation_rules_action_type_check
    CHECK (action_type IN ('public_reply', 'private_dm', 'ai_dm'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX idx_instagram_automation_rules_connection ON public.instagram_automation_rules (instagram_connection_id) WHERE enabled;
CREATE INDEX idx_instagram_automation_rules_org ON public.instagram_automation_rules (organization_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.instagram_automation_rules TO authenticated;
GRANT ALL ON public.instagram_automation_rules TO service_role;
ALTER TABLE public.instagram_automation_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant instagram automation rules" ON public.instagram_automation_rules
  FOR ALL TO authenticated
  USING (public.is_org_member(organization_id))
  WITH CHECK (public.is_org_member(organization_id));

CREATE TRIGGER trg_instagram_automation_rules_updated BEFORE UPDATE ON public.instagram_automation_rules
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- 5. instagram_comment_events — per-comment idempotency + audit ledger for
--    the comment automation path. This is the PRIMARY loop-protection
--    guard for comment->reply automation (spec item 12): a comment id is
--    processed at most once per connection, ever, full stop — a duplicate
--    webhook delivery, or a public reply that itself arrives back as a new
--    "comment" webhook event, can never trigger a second action because
--    the second insert simply fails its unique constraint. Server-only,
--    same as payment_webhook_events/payment_domain_events (no
--    authenticated grant at all — nothing in the customer dashboard reads
--    this in v1, keeping the automation UI itself minimal per spec).
-- ============================================================
CREATE TABLE public.instagram_comment_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  instagram_connection_id UUID NOT NULL REFERENCES public.instagram_connections(id) ON DELETE CASCADE,
  comment_id TEXT NOT NULL,
  matched_rule_id UUID REFERENCES public.instagram_automation_rules(id) ON DELETE SET NULL,
  action_taken TEXT NOT NULL DEFAULT 'none',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (instagram_connection_id, comment_id)
);

DO $$ BEGIN
  ALTER TABLE public.instagram_comment_events ADD CONSTRAINT instagram_comment_events_action_check
    CHECK (action_taken IN ('none', 'public_reply', 'private_dm', 'ai_dm', 'skipped_own_comment'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX idx_instagram_comment_events_org ON public.instagram_comment_events (organization_id);

REVOKE ALL ON public.instagram_comment_events FROM authenticated, anon;
GRANT ALL ON public.instagram_comment_events TO service_role;
ALTER TABLE public.instagram_comment_events ENABLE ROW LEVEL SECURITY;
-- No policies granted: server-only, exactly like payment_webhook_events /
-- payment_domain_events.

-- ============================================================
-- 6. Widen bookings.source to accept 'instagram' — additive only, the same
--    channel-tag vocabulary create_payment_required_booking already
--    accepts for voice/whatsapp/website/manual (see
--    booking-service.server.ts), extended so an Instagram-originated
--    booking (spec PART 14's worked example: "Instagram DM: 'I want an
--    appointment tomorrow at 5 PM.'") can be tagged accurately instead of
--    being forced into an inaccurate existing value. Does not touch any
--    existing bookings row or any other column.
-- ============================================================
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_source_check;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_source_check
  CHECK (source IN ('voice', 'whatsapp', 'website', 'manual', 'instagram'));

-- ============================================================
-- 7. Audit action vocabulary note (no schema change — writeAudit already
--    accepts a free-form action string; documenting the new ones Phase 5
--    code will use: INSTAGRAM_CONNECTED, INSTAGRAM_BOT_ASSIGNED,
--    INSTAGRAM_DISCONNECTED, INSTAGRAM_RECONNECT_FAILED)
-- ============================================================
