import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/**
 * Production incident (ref c49cabc1): createClientAccount's organizations
 * insert failed with Postgres 42501 "permission denied for sequence
 * org_client_id_seq". organizations.client_id is generated by a column
 * DEFAULT that calls nextval('public.org_client_id_seq') — the sequence
 * that migration created it with no accompanying GRANT, and a table-level
 * grant (GRANT ALL ON public.organizations TO service_role) does not
 * extend to a sequence referenced by one of that table's column defaults;
 * Postgres checks sequence privileges independently.
 *
 * Fix: grant only USAGE (the minimum nextval() requires) on this one
 * sequence, only to service_role.
 *
 * There is no live Postgres instance in this environment (no Supabase
 * project is connected here), so this cannot execute the GRANT or prove
 * runtime privilege enforcement. What it *can* prove, and does: the new
 * migration grants exactly USAGE (not a broader privilege) on exactly this
 * sequence, to exactly service_role, and does not touch anything else; and
 * the migrations this incident depends on were not edited to "fix" it a
 * different way (forward-only).
 */

const migrationsDir = dirname(fileURLToPath(import.meta.url));

const NEW_MIGRATION = join(migrationsDir, "20260911160000_grant_org_client_id_seq_usage.sql");
const SEQUENCE_MIGRATION = join(
  migrationsDir,
  "20260902060038_591a0810-758f-44e3-940d-5b8de002ffcd.sql",
);
const PROVISIONING_GRANTS_MIGRATION = join(
  migrationsDir,
  "20260905100000_restrict_organization_provisioning_grants.sql",
);

function readSql(path: string): string {
  return readFileSync(path, "utf8");
}

test("new migration grants exactly USAGE on org_client_id_seq to service_role", () => {
  const sql = readSql(NEW_MIGRATION);
  assert.match(sql, /GRANT USAGE ON SEQUENCE public\.org_client_id_seq TO service_role;/);
});

test("new migration does not grant a broader sequence privilege (SELECT/UPDATE/ALL) than USAGE requires", () => {
  const sql = readSql(NEW_MIGRATION);
  const grantLines = sql.split("\n").filter((l) => /^\s*GRANT\b/i.test(l));
  assert.equal(grantLines.length, 1, "expected exactly one GRANT statement in this migration");
  assert.doesNotMatch(grantLines[0]!, /\bSELECT\b|\bUPDATE\b|\bALL\b/);
});

test("new migration does not grant sequence usage to authenticated or anon", () => {
  const sql = readSql(NEW_MIGRATION);
  assert.doesNotMatch(sql, /TO authenticated/);
  assert.doesNotMatch(sql, /TO anon/);
});

test("new migration touches only the sequence — no RLS policy, table grant, or other object", () => {
  const sqlStatements = readSql(NEW_MIGRATION)
    .split("\n")
    .filter((l) => !l.trim().startsWith("--"))
    .join("\n");
  assert.doesNotMatch(
    sqlStatements,
    /\bCREATE POLICY\b|\bDROP POLICY\b|\bALTER TABLE\b|\bREVOKE\b|\bCREATE TABLE\b|\bCREATE INDEX\b/i,
  );
});

test("the sequence migration was not edited to add the grant retroactively (fix is forward-only)", () => {
  const sql = readSql(SEQUENCE_MIGRATION);
  assert.match(sql, /CREATE SEQUENCE IF NOT EXISTS public\.org_client_id_seq START 1;/);
  assert.doesNotMatch(sql, /GRANT.*org_client_id_seq/i);
});

test("the provisioning-grants migration (which revoked authenticated's organizations INSERT) was not edited", () => {
  const sql = readSql(PROVISIONING_GRANTS_MIGRATION);
  assert.match(sql, /REVOKE INSERT ON public\.organizations FROM authenticated;/);
});
